#!/bin/sh

# Start GOST in the background
# We assume gost.json exists (generated by the backend or a default one)
if [ ! -f "gost.json" ]; then
    echo "{}" > gost.json
fi

./gost-engine -C gost.json &

# Start the Panel Backend in the foreground
./gost-manager
